<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_PersistentDataManager" Id="{4ed47747-e9e7-4807-96fb-1abdb1959994}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PersistentDataManager
VAR PERSISTENT
	_PanelFrontLength :REAL;
	_Config : ST_REcipeBuilder_Config;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Config" Id="{1a5d92ef-6b65-43a4-903f-d617f66a22f2}">
      <Declaration><![CDATA[PROPERTY Config : ST_RecipeBuilder_Config]]></Declaration>
      <Get Name="Get" Id="{9300e8ec-af0f-4824-bd13-92b6592fc495}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Config := _Config;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{4e6adcec-48a4-45cf-8715-df36f2a76f6a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[_Config := Config;]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="FB_PersistentDataManager">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_PersistentDataManager.Config.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_PersistentDataManager.Config.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>