<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="SAFETY" Id="{35ba0ba9-0a5d-4f9c-a367-e8f271d5d193}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SAFETY
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SAFETY">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>